branches:
  - { name: main }
  - { name: v2, range: '2.x' }
  - { name: alpha, prerelease: true }
  - { name: beta, prerelease: true }
  - { name: rc, prerelease: true }
ci: true
debug: true
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: angular

  - - '@semantic-release/release-notes-generator'
    - preset: angular

  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md

  - - 'semantic-release-license'
    - license:
        path: LICENSE.md

  - - '@semantic-release/npm'
    - npmPublish: true

  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - LICENSE.md
        - package.json
        - package-lock.json
      message: "chore(release): v${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

  - - '@semantic-release/github'
    - addReleases: bottom
