# This workflow is responsible for building, testing and publishing the library when a new release tag is created.
# The workflow is composed by two jobs, `build` and `publish-npm`. The `build` job will build and test the code, and then,
# if everything is working correctly, it will try and publish the code to the specified registry.

name: npm release

on:
  release:
    types: [created]

env:
  node: 16.11

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: ${{ env.node }}
      - run: npm run ci:setup
      - run: npm run ci:build
      - run: npm run ci:test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: ${{ env.node }}
          registry-url: https://registry.npmjs.org/
          scope: '@odinjs'
      - run: npm run ci:setup
      - run: npm run ci:build
      - run: npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
